# Metadata about this component, to be used in the CMS
spec:
  structures:
    - container_blocks
    - content_blocks
  label: "Tight-container"
  description:
  icon: "notes"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  inner_content_blocks: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
