# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Cards"
  description: "A set of cards with an image, heading, and text"
  icon: "width_normal"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  cards:
    - media:
        image:
          url: ""
          alt: ""
      heading: 
        text: ""
        url: ""
      text: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: