# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Image-text-split"
  description:
  icon: "art_track"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image:
    url: /assets/basketball.jpg
    alt: Alt for image
  inner_content_blocks: []

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
